config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 #read all
 get 'tasks', to: 'tasks#index', as: :index
 #CRUD
 #C
 get 'tasks/new', to: 'tasks#new', as: :new
 post 'tasks', to: 'tasks#create'
 #R

 #read one
 get 'tasks/:id', to: 'tasks#show', as: :task
 #U
 get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
 patch 'tasks/:id', to: 'tasks#update'
 #D
 delete 'tasks/:id', to: 'tasks#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index         # GET /tasks
    @tasks = Task.all
  end

  def show          # GET /tasks/:id
    @task = Task.find(params[:id])
  end

  def new           # GET /tasks/new
    @task = Task.new
  end

  def create        # POST /tasks
    @task = Task.new(task_params)
    @task.save
    redirect_to index_path

  end

  def edit          # GET /tasks/:id/edit
    @task = Task.find(params[:id])
  end

  def update        # PATCH /tasks/:id
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to index_path
  end

  def destroy       # DELETE /tasks/:id
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to index_path

  end


  private
  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>

<% end %>

app/views/tasks/edit.html.erb
<%=  render 'form', task: @task %>

app/views/tasks/index.html.erb
<% @tasks.each do |task| %>
<ul>
  <li> <%= check_box("tag", tag.id, {checked: task.completed}) %> <%= link_to task.title, task_path(task) %> <%= button_to "X", destroy_path(task.id), :method => "delete", data: { confirm: "Are you sure?" } %> </li>
</ul>


<% end %>

<%= link_to "+ add a new taks", new_path  %>

app/views/tasks/new.html.erb
<%=  render 'form', task: @task %>


<%= link_to "back to list", index_path  %>

app/views/tasks/show.html.erb
<%= button_to "Edit my task", edit_path, :method => 'get' %>


<p> <%= @task.details %> </p>

<%= link_to 'go back', index_path  %>